name: splicing-pipelines-nf
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - fastqc=0.11.9
  - trimmomatic=0.39
  - star=2.7.3
  - samtools=1.10
  - deeptools=3.4.0
  - multiqc=1.8
  - gffread=0.11.7
  - bioconductor-rtracklayer=1.46.0

# Now installed via executable in `Dockerfile`
  # - stringtie=2.1.2
  # - gffcompare=0.11.2